### ISSUE TITLE
Segmentation Fault when opening file

### ISSUE THREAD

**Issue by thoduv** [rs1909/knut#1] opened 2017-03-23 15:55 UTC
Hello,

I'm trying to use Knut, so I have compiled it from the latest git version. Unfortunately, I get a "Segmentation Fault" error every time I try to open a file. This seems to be an error in the parser, but I can't find exactly where.
I have attached the backtrace I get when I run "gdb knut".

Thanks !

[knut_backtrace.txt](https://github.com/rs1909/knut/files/865216/knut_backtrace.txt)

**Comment by rs1909** [comment] 2017-03-24 13:19
Thanks for reporting. Could you please attach the files your are trying to open? Both the .knut and the .vf file. Otherwise there is no way for me to reproduce this.

**Comment by thoduv** [comment] 2017-03-24 14:02
Hello.
I have only tried with the files from the "demo" directory, and it crashes with any of them.

**Comment by rs1909** [comment] 2017-03-24 14:39
In that case I cannot reproduce this, since all of those are working for me on all three platforms. You might have checked out a version that was between two intermediate commits. I suggest to update to the current version that should work. There is a test-all.sh in the source tree, if you have knut-cli on your $PATH that will test all the demos.

**Comment by thoduv** [comment] 2017-03-24 15:06
Thanks for you answer. I have tried to update my repository, and also to download older releases, and the problem is there all the time.

With "./test-all.sh", I get errors for every test :
"Critical error (err == 0) has failed. Error changing directory. This has occurred in file '/cli/main.cpp' at line 56."

But if I try to manually use knut-cli, it works great. For instance, "knut-cli -c cfile-start.knut" in the "simple_laser" demo works fine.
So I guess this is a gui-related problem..?

**Comment by rs1909** [comment] 2017-03-24 16:17
"./test-all.sh" would test the CLI. It tests the installed knut, after you have run "make install". My suspicion is that you've missed "make install" and the test cannot find the installation.

The crash in GUI is bizarre. The backtrace implies that the crash is in the c++ standard library and happens already in the tokeniser after trying to convert a number to double. However the GUI and CLI use the same code, so the other suspicion is that the GUI corrupts the memory somewhere.

But again, I've tried and the GUI works on my computers and now on one of my students computer as well, so the difference is probably in the libraries you have installed on your system.

**Comment by rs1909** [comment] 2017-03-27 12:46
Since this does not seem to occur elsewhere, I am closing this issue. If you could not resolve this, please open a new issue.

**Closed as completed by rs1909** 2017-03-27 12:46 UTC
