### ISSUE TITLE
Segmentation Fault/Out of Memory when opening file in GUI

### ISSUE THREAD

**Issue by thoduv** [rs1909/knut#2] opened 2017-04-26 09:01 UTC
Hello !

This is the same issue again : https://github.com/rs1909/knut/issues/1

I've spent a lot of time last week trying to find out where this crash comes from. Sure I've learnt a lot on gdb, valgrind, etc, but in the end I could not solve the problem.
I've also tried different versions of knut, different versions of Qt, but I could not get it to work.

Do you think you could tell me some details about your setup ? Distrib, Qt version, gcc version, etc. Do you have any statically linked working version ?
Or even a Windows version ?

By the way, links on the home page are broken : http://rs1909.github.io/knut/

Thanks for your help ! I need to do some DDE continuation analysis, and software for this kind of thing is quite rare !

**Comment by rs1909** [comment] 2017-08-02 10:57
I use Fedora 26 at the moment, but it also worked with all other Fedoras before. I was unable to make a statically linked version, cmake just did not want to cooperate on this. 

The necessary packages are: cmake, mxml-devel, gcc, gcc-c++, gcc-gfortran, libgfortran-static, openblas-* (all of opneblas), qt5-* (all of qt5).

The download links work again. The windows version was tested by students, I have no access to Windows, but it works under Wine.

Sorry for the slow reply, for some reason I did not get a notification of this issue. You might be better off using DDE-BIFTOOL, even though entering the equations there is a pain.

**Comment by rs1909** [comment] 2017-08-14 09:17
Since this is not reproducible I'll close the issue.

**Closed as completed by rs1909** 2017-08-14 09:17 UTC
